### ISSUE TITLE
Memory leak on node 0.12.6 beaglebone black? 

### ISSUE THREAD

**Issue by jacobrosenthal** [voodootikigod/node-serialport#598] opened 2015-09-30 01:19 UTC
Reported by @keyvanfatehi here https://github.com/voodootikigod/node-serialport/issues/579#issuecomment-140526607

**Comment by keyvanfatehi** [comment] 2015-09-30 18:07
@jacobrosenthal I'd think that since switching to iojs 2.5.0 (from node 0.12.6) fixed the leak, it may or may not have been node-serialport and even if it was, whatever the cause it was probably out of scope of node-serialport [rather it was probably in node itself]. Thus we can probably close the issue. What do you think?

I'll keep an eye on #578 (node 4 support) and report if I experience any leaks with that. I wish I had profiled deeply enough to prove it was node-serialport, but I didn't and don't see reasonable incentive to go do that at this time.

**Closed** 2016-03-31 15:54 UTC
